version: '2'
services:
  healthcheck:
    labels:
      io.rancher.container.create_agent: 'true'
      io.rancher.scheduler.global: 'true'
    image: vyushmanov/rancher-healthcheck:v0.4
    command: healthcheck --metadata-address 169.254.169.250
    logging:
      driver: json-file
      options:
        max-size: 25m
        max-file: '2'
