.catalog:
  name: "Healthcheck Service"
  version: "v0.4"
  description: "Rancher healthcheck service"
  minimum_rancher_version: v1.6.19-rc1
healthcheck:
  health_check:
      port: 42
      interval: 2000
      response_timeout: 2000
      unhealthy_threshold: 3
      healthy_threshold: 2
      initializing_timeout: 60000
      reinitializing_timeout: 60000
