name: Healthcheck Service
description: Rancher healthcheck service
version: v0.4
category: Framework
projectURL: https://github.com/vvyushmanov/rancher-healthcheck
labels:
  io.rancher.certified: rancher
  io.rancher.orchestration.supported: 'cattle,mesos,swarm,kubernetes'
